/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckInQrTokenRouteImport } from './routes/check-in.$qrToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInQrTokenRoute = CheckInQrTokenRouteImport.update({
  id: '/check-in/$qrToken',
  path: '/check-in/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in/$qrToken': typeof CheckInQrTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in/$qrToken': typeof CheckInQrTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in/$qrToken': typeof CheckInQrTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/check-in/$qrToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/check-in/$qrToken'
  id: '__root__' | '/' | '/check-in/$qrToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInQrTokenRoute: typeof CheckInQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/$qrToken': {
      id: '/check-in/$qrToken'
      path: '/check-in/$qrToken'
      fullPath: '/check-in/$qrToken'
      preLoaderRoute: typeof CheckInQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInQrTokenRoute: CheckInQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
